GET http://localhost:8080/api/racingteams/95f4136e-a39e-4f94-8f5b-8a457ec6b916/drivers
Accept: application/json

###
POST http://localhost:8080/api/racingteams/95f4136e-a39e-4f94-8f5b-8a457ec6b916/drivers
Content-Type: application/json

{
  "firstName": "first",
  "lastName": "last",
  "age": 5,
  "birthday": "2022-03-15T15:30:22.000Z"
}

###
GET http://localhost:8080/api/racingteams
Accept: application/json

###
POST http://localhost:8080/api/racingteams
Content-Type: application/json

{
  "name": "Team 1"
}

###

