spring:
  datasource:
    url: "jdbc:postgresql://database-1.cluster-czgav0s4nmda.eu-central-1.rds.amazonaws.com/clickops"
    username: "postgres"
    password: "clickops1337"
  jpa:
    generate-ddl: true
