spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:15432/
    username: ninja-guy # DB user
    password: inTheSh4d0ws # DB password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
