spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://springtraining9.czgav0s4nmda.eu-central-1.rds.amazonaws.com:5432/
    username: spring # DB user
    password: UBbqxJGzt4aq-nCYdmPm # DB password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
