GET http://localhost:8080/health

###

GET http://localhost:8080/teams
Accept: application/json

###

POST http://localhost:8080/teams
Content-Type: application/json

{
  "name": "best racing team",
  "drivers": [
    {
      "firstName": "John",
      "lastName": "Doe",
      "dateOfBirth": "1978-07-23"
    }
  ]
}




